### ISSUE TITLE
./hrtool -i and ./hrtool -b errors

### ISSUE THREAD

**Issue by edpell** [hansonrobotics/hansoncog#1]
./hrtool -i gives
Hit http://security.ubuntu.com vivid-security/restricted Translation-en
Hit http://security.ubuntu.com vivid-security/universe Translation-en
Fetched 3,527 B in 8s (392 B/s)                                                                                        
W: Failed to fetch http://ppa.launchpad.net/opencog-dev/ppa/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/opencog-dev/ppa/ubuntu/dists/vivid/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

./hrtool -b gives 
ed@edlinux:~/hansoncog/scripts$ ./hrtool -b
./hrtool: line 167: cd: /home/ed/hansonrobotics/hansoncog: No such file or directory

**Comment by vytasrgl** [comment]
@edpell 
Ubuntu 14.04 should be used. Sorry won't work on never versions as ROS Indigo is not supported on never versions.

**Comment by vytasrgl** [comment]
Updated on README
